export interface DllInfo {
  name: string;
  stem: string;
  description: string;
  category: DllCategory;
  introduced: string;
  retired: string | null;
  path: string;
}

export type DllCategory =
  | "shell"
  | "network"
  | "devices"
  | "media"
  | "system"
  | "legacy"
  | "modern-ui";

export const DLL_REGISTRY: Record<string, DllInfo> = {
  progman: {
    name: "progman.exe",
    stem: "progman",
    description: "Program Manager — general category icons",
    category: "legacy",
    introduced: "win31",
    retired: "win98",
    path: "%SystemRoot%\\progman.exe",
  },
  moricons: {
    name: "moricons.dll",
    stem: "moricons",
    description: "Icons for popular 3rd-party DOS apps (Lotus 1-2-3, WordPerfect, etc.)",
    category: "legacy",
    introduced: "win31",
    retired: null,
    path: "%SystemRoot%\\System32\\moricons.dll",
  },
  shell32: {
    name: "shell32.dll",
    stem: "shell32",
    description: "Core shell icons — folders, drives, actions",
    category: "shell",
    introduced: "win95",
    retired: null,
    path: "%SystemRoot%\\System32\\shell32.dll",
  },
  explorer: {
    name: "explorer.exe",
    stem: "explorer",
    description: "Windows Explorer-specific icons",
    category: "shell",
    introduced: "win95",
    retired: null,
    path: "%SystemRoot%\\explorer.exe",
  },
  pifmgr: {
    name: "pifmgr.dll",
    stem: "pifmgr",
    description: 'DOS/PIF shortcut icons — created "just for fun" per Raymond Chen',
    category: "legacy",
    introduced: "win95",
    retired: null,
    path: "%SystemRoot%\\System32\\pifmgr.dll",
  },
  mshtml: {
    name: "mshtml.dll",
    stem: "mshtml",
    description: "Internet Explorer HTML rendering icons",
    category: "network",
    introduced: "win95",
    retired: "winxp",
    path: "%SystemRoot%\\System32\\mshtml.dll",
  },
  ieframe: {
    name: "ieframe.dll",
    stem: "ieframe",
    description: "Internet Explorer frame & toolbar icons",
    category: "network",
    introduced: "winxp",
    retired: "win11",
    path: "%SystemRoot%\\System32\\ieframe.dll",
  },
  xpsp2res: {
    name: "xpsp2res.dll",
    stem: "xpsp2res",
    description: "Security Center & SP2 feature icons",
    category: "system",
    introduced: "winxp",
    retired: "win11",
    path: "%SystemRoot%\\System32\\xpsp2res.dll",
  },
  compstui: {
    name: "compstui.dll",
    stem: "compstui",
    description: "Printing & color composition UI icons",
    category: "system",
    introduced: "winxp",
    retired: null,
    path: "%SystemRoot%\\System32\\compstui.dll",
  },
  wmploc: {
    name: "wmploc.dll",
    stem: "wmploc",
    description: "Windows Media Player icons",
    category: "media",
    introduced: "winxp",
    retired: null,
    path: "%SystemRoot%\\System32\\wmploc.dll",
  },
  netshell: {
    name: "netshell.dll",
    stem: "netshell",
    description: "Network connection & adapter icons",
    category: "network",
    introduced: "winxp",
    retired: null,
    path: "%SystemRoot%\\System32\\netshell.dll",
  },
  mmcndmgr: {
    name: "mmcndmgr.dll",
    stem: "mmcndmgr",
    description: "Management Console snap-in icons",
    category: "system",
    introduced: "winxp",
    retired: null,
    path: "%SystemRoot%\\System32\\mmcndmgr.dll",
  },
  imageres: {
    name: "imageres.dll",
    stem: "imageres",
    description: "Primary icon store (Vista+) — devices, actions, status",
    category: "shell",
    introduced: "winvista",
    retired: null,
    path: "%SystemRoot%\\System32\\imageres.dll",
  },
  ddores: {
    name: "DDORes.dll",
    stem: "ddores",
    description: "Devices & Printers icons",
    category: "devices",
    introduced: "winvista",
    retired: null,
    path: "%SystemRoot%\\System32\\DDORes.dll",
  },
  setupapi: {
    name: "setupapi.dll",
    stem: "setupapi",
    description: "Device driver & setup icons",
    category: "devices",
    introduced: "winvista",
    retired: null,
    path: "%SystemRoot%\\System32\\setupapi.dll",
  },
  accessibilitycpl: {
    name: "accessibilitycpl.dll",
    stem: "accessibilitycpl",
    description: "Accessibility / Ease of Access icons",
    category: "system",
    introduced: "win7",
    retired: null,
    path: "%SystemRoot%\\System32\\accessibilitycpl.dll",
  },
  twinui: {
    name: "twinui.dll",
    stem: "twinui",
    description: "Modern UI / Metro app icons",
    category: "modern-ui",
    introduced: "win8",
    retired: null,
    path: "%SystemRoot%\\System32\\twinui.dll",
  },
  pnidui: {
    name: "pnidui.dll",
    stem: "pnidui",
    description: "Network tray & status animations",
    category: "network",
    introduced: "win10",
    retired: null,
    path: "%SystemRoot%\\System32\\pnidui.dll",
  },
  vault: {
    name: "Vault.dll",
    stem: "vault",
    description: "Credential Manager / vault icons",
    category: "system",
    introduced: "win10",
    retired: null,
    path: "%SystemRoot%\\System32\\Vault.dll",
  },
  wdc: {
    name: "wdc.dll",
    stem: "wdc",
    description: "Windows Defender Center icons",
    category: "system",
    introduced: "win10",
    retired: null,
    path: "%SystemRoot%\\System32\\wdc.dll",
  },
  connect: {
    name: "connect.dll",
    stem: "connect",
    description: "Connect (cast/project) icons",
    category: "devices",
    introduced: "win10",
    retired: null,
    path: "%SystemRoot%\\System32\\connect.dll",
  },
  themecpl: {
    name: "themecpl.dll",
    stem: "themecpl",
    description: "Theme & personalization icons",
    category: "system",
    introduced: "win10",
    retired: null,
    path: "%SystemRoot%\\System32\\themecpl.dll",
  },
  user32: {
    name: "user32.dll",
    stem: "user32",
    description: "Core USER subsystem icons (cursors, etc.)",
    category: "system",
    introduced: "win10",
    retired: null,
    path: "%SystemRoot%\\System32\\user32.dll",
  },
  "twinui.pcshell": {
    name: "twinui.pcshell.dll",
    stem: "twinui.pcshell",
    description: "Start menu & taskbar icons (split from twinui)",
    category: "modern-ui",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\twinui.pcshell.dll",
  },
  // Win11-only DLLs already in the existing index
  aclui: {
    name: "aclui.dll",
    stem: "aclui",
    description: "Access control list editor icons",
    category: "system",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\aclui.dll",
  },
  autoplay: {
    name: "autoplay.dll",
    stem: "autoplay",
    description: "AutoPlay handler icons",
    category: "shell",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\autoplay.dll",
  },
  comctl32: {
    name: "comctl32.dll",
    stem: "comctl32",
    description: "Common controls library icons",
    category: "system",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\comctl32.dll",
  },
  comres: {
    name: "comres.dll",
    stem: "comres",
    description: "COM+ resource icons",
    category: "system",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\comres.dll",
  },
  dmdskres: {
    name: "dmdskres.dll",
    stem: "dmdskres",
    description: "Disk Management snap-in icons",
    category: "system",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\dmdskres.dll",
  },
  dsuiext: {
    name: "dsuiext.dll",
    stem: "dsuiext",
    description: "Active Directory UI extension icons",
    category: "system",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\dsuiext.dll",
  },
  mmres: {
    name: "mmres.dll",
    stem: "mmres",
    description: "Multimedia resource icons",
    category: "media",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\mmres.dll",
  },
  mstsc: {
    name: "mstsc.exe",
    stem: "mstsc",
    description: "Remote Desktop Connection icons",
    category: "network",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\mstsc.exe",
  },
  mstscax: {
    name: "mstscax.dll",
    stem: "mstscax",
    description: "Remote Desktop ActiveX control icons",
    category: "network",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\mstscax.dll",
  },
  ncpa: {
    name: "ncpa.cpl",
    stem: "ncpa",
    description: "Network Connections control panel icons",
    category: "network",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\ncpa.cpl",
  },
  netcenter: {
    name: "netcenter.dll",
    stem: "netcenter",
    description: "Network and Sharing Center icons",
    category: "network",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\netcenter.dll",
  },
  networkexplorer: {
    name: "networkexplorer.dll",
    stem: "networkexplorer",
    description: "Network Explorer icons",
    category: "network",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\networkexplorer.dll",
  },
  sensorscpl: {
    name: "sensorscpl.dll",
    stem: "sensorscpl",
    description: "Sensors control panel icons",
    category: "devices",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\sensorscpl.dll",
  },
  url: {
    name: "url.dll",
    stem: "url",
    description: "Internet shortcut icons",
    category: "network",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\url.dll",
  },
  wiashext: {
    name: "wiashext.dll",
    stem: "wiashext",
    description: "Windows Image Acquisition shell extension icons",
    category: "devices",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\wiashext.dll",
  },
  wpdshext: {
    name: "wpdshext.dll",
    stem: "wpdshext",
    description: "Portable Devices shell extension icons",
    category: "devices",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\wpdshext.dll",
  },
  xwizards: {
    name: "xwizards.dll",
    stem: "xwizards",
    description: "Extensible Wizards framework icons",
    category: "system",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\xwizards.dll",
  },
  actioncentercpl: {
    name: "actioncentercpl.dll",
    stem: "actioncentercpl",
    description: "Action Center control panel icons",
    category: "system",
    introduced: "win11",
    retired: null,
    path: "%SystemRoot%\\System32\\actioncentercpl.dll",
  },
};

export function getDllInfo(stem: string): DllInfo | undefined {
  return DLL_REGISTRY[stem.toLowerCase()];
}

export function getDllDescription(stem: string): string {
  return DLL_REGISTRY[stem.toLowerCase()]?.description ?? "";
}

export function getDllCategory(stem: string): DllCategory | "" {
  return DLL_REGISTRY[stem.toLowerCase()]?.category ?? "";
}

export const DLL_CATEGORY_LABELS: Record<DllCategory, string> = {
  shell: "Shell & Explorer",
  network: "Network & Internet",
  devices: "Devices & Hardware",
  media: "Media & Multimedia",
  system: "System & Management",
  legacy: "Legacy / DOS Compatibility",
  "modern-ui": "Modern UI / Metro",
};
